#!/bin/sh
# Unites RFC3339, RFC3875, RFC8536, and IEEE 1003 (POSIX).
# An available TZDATA timezone database makes this program much more useful:
# allowing for input like "America/Los_Angeles" instead of "PST8PDT".

if test "$QUERY_STRING" != ''
then 1="$QUERY_STRING"
fi

printf '%s\n\n%s\n' \
       "content-type: text/plain" \
       "$(TZ=$1 date '+%Y-%m-%dT%H:%M:%S%z' | sed 's@^.\{22\}@&:@')"
       # The sed command corrects timezone offset formatting.
